### ISSUE TITLE
How to install htp module?

### ISSUE THREAD

**Issue by amseram** [jkitchin/python-torque#1]
When I try to import torque in python shell, the below info will be shown: 
import torque
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "torque/__init__.py", line 17, in <module>
    from torque import *
  File "torque/torque.py", line 11, in <module>
    from htp.ssh import ssh
ImportError: No module named htp.ssh
How could I fix this problem?

**Comment by jkitchin** [comment]
you might be able to install it from here: https://github.com/jkitchin/htp

This is quite old code though, I am not supporting it anymore, and not sure it will still work.

**Comment by amseram** [comment]
I appreciate it very much. And you are right, I need import "exceptions" in torque.py. Finally, it is working well, Thx very much!
